services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile

  infrastructure:
    image: infrastructure
    build:
      context: .
      dockerfile: Infrastructure/Dockerfile
