version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: taskflow-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow_network

volumes:
  postgres_data:

networks:
  taskflow_network:
