name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DEFAULT_CONNECTION=${{ secrets.DEFAULT_CONNECTION }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
          server: "https://${{ secrets.CAPROVER_SERVER }}"
          app: ${{ secrets.CAPROVER_APP_PROD }}
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
